import localFont from 'next/font/local'
import './globals.css'
import {cn} from "../utils/cn";

const inter = localFont({ src: '../../public/fonts/FontsFree-Net-Baloo2-Bold-1.ttf' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(inter.className , 'flex items-start justify-start ')} >
        {children}
      </body>
    </html>
  )
}
